= Welcome to  iet-hf-2024-sauna contributing guide

In this guide you will get an overview of the contribution workflow from opening an issue, creating a PRfootnote:[Pull Request], reviewing and merging the PR.

== Introduction

The issue structure of this repository is quite bizarre due to its requirements.

A limited number of main issues are used to track the few tasks given to its maintainers.
If you wish to add a new issue related to these, please use the task list feature as described https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists[here].

== Issues

Before creating a new issue, please check whether a related issue already exists.

Feel free to reply to an issue as a form of communication.

Upon resolving an issue, either reference it in the commit message or PR as described https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword[here], or link the PR/commit when closing the issue.

== Pull requests

After completing a main task/issue, open a pull request, so that someone else can review it as written in the homework requirements.

The main tasks will all get their own feature branches.
These branches can only be merged to main via reviewed PRs.

Additional branches can be created if necessary.
